/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinkedList */

#ifndef _Included_LinkedList
#define _Included_LinkedList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LinkedList
 * Method:    rdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_LinkedList_rdtsc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
